name:                interpreter
version:             0.1.0.0
github:              "lorenzleutgeb/lac"
license:             GPL-3
author:              "Lorenz Leutgeb"
maintainer:          "lorenz@leutgeb.xyz"
copyright:           "2019 Lorenz Leutgeb"

#synopsis:            Short description of your package
#category:            Web

description:         Please see the README on GitHub at <https://github.com/lorenzleutgeb/lax#readme>

dependencies:
- base >= 4.7 && < 5

custom-setup:
  dependencies:
  - base
  - process >= 1.6.5.1
  - Cabal >= 3.0 && < 4.0

library:
  source-dirs:
  - src
  - generated-src
  default-extensions:
  - GADTs
  - FlexibleContexts
  - DeriveFunctor

#executables:
#  interpreter:
#    main:                Main.hs
#    source-dirs:         app
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - interpreter

tests:
  interpreter-test:
    main: Spec.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - interpreter
    - HUnit
